name: LumaJDA
version: '${project.version}'
main: dev.jsinco.lumajda.LumaJDA
api-version: '1.20'
description: 'API for my other plugins to interface with JDA and DiscordSRV'
softdepend: [DiscordSRV]
commands:
  lumajdarl:
    description: 'Reloads the LumaJDA config and JDA'
    usage: /<command>
    permission: lumajda.command.reload
